# 网络请求设置
request:
  timeout: 10 # 超时设置
  ssl: false # ssl设置

# 要抓取的 issues 配置
issues:
  repo: BeaCox/friendLink # 仓库持有者/仓库名
  # 第一步筛选，state
  state: closed # 留空则从所有issue中抓取，open则从所有open的issue中抓取，closed从所有closed的issue中抓取
  # 第二步筛选，label
  label: active  # 只能配置1个或留空，留空则所有满足`state`的issue都会被抓取。配置1个时，issue只有在具有该标签时才被抓取
  groups: # 填写用来分组的label名称。留空则所有被抓取的issue输出至data.json，否则按照输出与组名同名的json文件
    - bro
    - closer
    - e-friend
  sort: updated-desc # 排序，按最近更新，取消此项则按创建时间排序
